/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\indexes-theme.ts
 * Command: astryx theme build src\themes\indexes-theme.ts
 * Generated: 2026-10-08T19:19:02.615Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const indexesTheme: DefinedTheme;
