/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\indexes-theme.ts
 * Command: astryx theme build src\themes\indexes-theme.ts
 * Generated: 2026-10-08T19:19:02.703Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface XDSBadgeVariantMap {
    'gray': true;
  }
}
