/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\storefront.ts
 * Command: astryx theme build src\themes\storefront.ts
 * Generated: 2026-09-24T17:36:22.684Z
 */

import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const indexesStorefrontTheme: DefinedTheme;
