/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ImmersiveStoreRouteImport } from './routes/immersive-store'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as VendorSlugRouteImport } from './routes/vendor.$slug'
import { Route as StoreSettingsRouteImport } from './routes/store.settings'
import { Route as StoreProductsRouteImport } from './routes/store.products'
import { Route as StoreOrdersRouteImport } from './routes/store.orders'
import { Route as StoreMarketingRouteImport } from './routes/store.marketing'
import { Route as StoreInventoryRouteImport } from './routes/store.inventory'
import { Route as StoreEarningsRouteImport } from './routes/store.earnings'
import { Route as StoreDashboardRouteImport } from './routes/store.dashboard'
import { Route as StoreCustomersRouteImport } from './routes/store.customers'
import { Route as StoreAnalyticsRouteImport } from './routes/store.analytics'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as GoogleShoppingXmlRouteImport } from './routes/google-shopping.xml'
import { Route as Demo3dViewerRouteImport } from './routes/demo.3d-viewer'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStudioRouteImport } from './routes/admin.studio'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminStorefrontRouteImport } from './routes/admin.storefront'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAppearanceRouteImport } from './routes/admin.appearance'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks.whatsapp'
import { Route as ApiPublicImageProxyRouteImport } from './routes/api/public.image-proxy'
import { Route as ApiAiAnalyzeProductRouteImport } from './routes/api/ai.analyze-product'
import { Route as AdminStoresTenantIdRouteImport } from './routes/admin.stores.$tenantId'
import { Route as AdminProductIdRouteImport } from './routes/admin.product.$id'
import { Route as AdminIntegrationsWhatsappRouteImport } from './routes/admin.integrations.whatsapp'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmersiveStoreRoute = ImmersiveStoreRouteImport.update({
  id: '/immersive-store',
  path: '/immersive-store',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSlugRoute = VendorSlugRouteImport.update({
  id: '/vendor/$slug',
  path: '/vendor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSettingsRoute = StoreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductsRoute = StoreProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMarketingRoute = StoreMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => StoreRoute,
} as any)
const StoreInventoryRoute = StoreInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEarningsRoute = StoreEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDashboardRoute = StoreDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCustomersRoute = StoreCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAnalyticsRoute = StoreAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StoreRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleShoppingXmlRoute = GoogleShoppingXmlRouteImport.update({
  id: '/google-shopping/xml',
  path: '/google-shopping/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo3dViewerRoute = Demo3dViewerRouteImport.update({
  id: '/demo/3d-viewer',
  path: '/demo/3d-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudioRoute = AdminStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorefrontRoute = AdminStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageProxyRoute = ApiPublicImageProxyRouteImport.update({
  id: '/api/public/image-proxy',
  path: '/api/public/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyzeProductRoute = ApiAiAnalyzeProductRouteImport.update({
  id: '/api/ai/analyze-product',
  path: '/api/ai/analyze-product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoresTenantIdRoute = AdminStoresTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AdminStoresRoute,
} as any)
const AdminProductIdRoute = AdminProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsWhatsappRoute =
  AdminIntegrationsWhatsappRouteImport.update({
    id: '/integrations/whatsapp',
    path: '/integrations/whatsapp',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/immersive-store': typeof ImmersiveStoreRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/store': typeof StoreRouteWithChildren
  '/track': typeof TrackRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/storefront': typeof AdminStorefrontRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/studio': typeof AdminStudioRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$id': typeof CategoryIdRoute
  '/demo/3d-viewer': typeof Demo3dViewerRoute
  '/google-shopping/xml': typeof GoogleShoppingXmlRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/store/analytics': typeof StoreAnalyticsRoute
  '/store/customers': typeof StoreCustomersRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/earnings': typeof StoreEarningsRoute
  '/store/inventory': typeof StoreInventoryRoute
  '/store/marketing': typeof StoreMarketingRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/store/settings': typeof StoreSettingsRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/integrations/whatsapp': typeof AdminIntegrationsWhatsappRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/stores/$tenantId': typeof AdminStoresTenantIdRoute
  '/api/ai/analyze-product': typeof ApiAiAnalyzeProductRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/immersive-store': typeof ImmersiveStoreRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/track': typeof TrackRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/storefront': typeof AdminStorefrontRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/studio': typeof AdminStudioRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$id': typeof CategoryIdRoute
  '/demo/3d-viewer': typeof Demo3dViewerRoute
  '/google-shopping/xml': typeof GoogleShoppingXmlRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/store/analytics': typeof StoreAnalyticsRoute
  '/store/customers': typeof StoreCustomersRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/earnings': typeof StoreEarningsRoute
  '/store/inventory': typeof StoreInventoryRoute
  '/store/marketing': typeof StoreMarketingRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/store/settings': typeof StoreSettingsRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/store': typeof StoreIndexRoute
  '/admin/integrations/whatsapp': typeof AdminIntegrationsWhatsappRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/stores/$tenantId': typeof AdminStoresTenantIdRoute
  '/api/ai/analyze-product': typeof ApiAiAnalyzeProductRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/immersive-store': typeof ImmersiveStoreRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/store': typeof StoreRouteWithChildren
  '/track': typeof TrackRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/storefront': typeof AdminStorefrontRoute
  '/admin/stores': typeof AdminStoresRouteWithChildren
  '/admin/studio': typeof AdminStudioRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$id': typeof CategoryIdRoute
  '/demo/3d-viewer': typeof Demo3dViewerRoute
  '/google-shopping/xml': typeof GoogleShoppingXmlRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/store/analytics': typeof StoreAnalyticsRoute
  '/store/customers': typeof StoreCustomersRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/earnings': typeof StoreEarningsRoute
  '/store/inventory': typeof StoreInventoryRoute
  '/store/marketing': typeof StoreMarketingRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/store/settings': typeof StoreSettingsRoute
  '/vendor/$slug': typeof VendorSlugRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/integrations/whatsapp': typeof AdminIntegrationsWhatsappRoute
  '/admin/product/$id': typeof AdminProductIdRoute
  '/admin/stores/$tenantId': typeof AdminStoresTenantIdRoute
  '/api/ai/analyze-product': typeof ApiAiAnalyzeProductRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/immersive-store'
    | '/offers'
    | '/onboarding'
    | '/search'
    | '/store'
    | '/track'
    | '/admin/appearance'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/deals'
    | '/admin/insights'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/platform'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/storefront'
    | '/admin/stores'
    | '/admin/studio'
    | '/admin/users'
    | '/category/$id'
    | '/demo/3d-viewer'
    | '/google-shopping/xml'
    | '/pages/$slug'
    | '/product/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/store/analytics'
    | '/store/customers'
    | '/store/dashboard'
    | '/store/earnings'
    | '/store/inventory'
    | '/store/marketing'
    | '/store/orders'
    | '/store/products'
    | '/store/settings'
    | '/vendor/$slug'
    | '/vendor/dashboard'
    | '/admin/'
    | '/store/'
    | '/admin/integrations/whatsapp'
    | '/admin/product/$id'
    | '/admin/stores/$tenantId'
    | '/api/ai/analyze-product'
    | '/api/public/image-proxy'
    | '/api/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/immersive-store'
    | '/offers'
    | '/onboarding'
    | '/search'
    | '/track'
    | '/admin/appearance'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/deals'
    | '/admin/insights'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/platform'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/storefront'
    | '/admin/stores'
    | '/admin/studio'
    | '/admin/users'
    | '/category/$id'
    | '/demo/3d-viewer'
    | '/google-shopping/xml'
    | '/pages/$slug'
    | '/product/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/store/analytics'
    | '/store/customers'
    | '/store/dashboard'
    | '/store/earnings'
    | '/store/inventory'
    | '/store/marketing'
    | '/store/orders'
    | '/store/products'
    | '/store/settings'
    | '/vendor/$slug'
    | '/vendor/dashboard'
    | '/admin'
    | '/store'
    | '/admin/integrations/whatsapp'
    | '/admin/product/$id'
    | '/admin/stores/$tenantId'
    | '/api/ai/analyze-product'
    | '/api/public/image-proxy'
    | '/api/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/immersive-store'
    | '/offers'
    | '/onboarding'
    | '/search'
    | '/store'
    | '/track'
    | '/admin/appearance'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/deals'
    | '/admin/insights'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/platform'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/seo'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/storefront'
    | '/admin/stores'
    | '/admin/studio'
    | '/admin/users'
    | '/category/$id'
    | '/demo/3d-viewer'
    | '/google-shopping/xml'
    | '/pages/$slug'
    | '/product/$slug'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/store/analytics'
    | '/store/customers'
    | '/store/dashboard'
    | '/store/earnings'
    | '/store/inventory'
    | '/store/marketing'
    | '/store/orders'
    | '/store/products'
    | '/store/settings'
    | '/vendor/$slug'
    | '/vendor/dashboard'
    | '/admin/'
    | '/store/'
    | '/admin/integrations/whatsapp'
    | '/admin/product/$id'
    | '/admin/stores/$tenantId'
    | '/api/ai/analyze-product'
    | '/api/public/image-proxy'
    | '/api/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ImmersiveStoreRoute: typeof ImmersiveStoreRoute
  OffersRoute: typeof OffersRoute
  OnboardingRoute: typeof OnboardingRoute
  SearchRoute: typeof SearchRoute
  StoreRoute: typeof StoreRouteWithChildren
  TrackRoute: typeof TrackRoute
  CategoryIdRoute: typeof CategoryIdRoute
  Demo3dViewerRoute: typeof Demo3dViewerRoute
  GoogleShoppingXmlRoute: typeof GoogleShoppingXmlRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  VendorSlugRoute: typeof VendorSlugRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  ApiAiAnalyzeProductRoute: typeof ApiAiAnalyzeProductRoute
  ApiPublicImageProxyRoute: typeof ApiPublicImageProxyRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immersive-store': {
      id: '/immersive-store'
      path: '/immersive-store'
      fullPath: '/immersive-store'
      preLoaderRoute: typeof ImmersiveStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$slug': {
      id: '/vendor/$slug'
      path: '/vendor/$slug'
      fullPath: '/vendor/$slug'
      preLoaderRoute: typeof VendorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/settings': {
      id: '/store/settings'
      path: '/settings'
      fullPath: '/store/settings'
      preLoaderRoute: typeof StoreSettingsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/products': {
      id: '/store/products'
      path: '/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof StoreProductsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/orders': {
      id: '/store/orders'
      path: '/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/marketing': {
      id: '/store/marketing'
      path: '/marketing'
      fullPath: '/store/marketing'
      preLoaderRoute: typeof StoreMarketingRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/inventory': {
      id: '/store/inventory'
      path: '/inventory'
      fullPath: '/store/inventory'
      preLoaderRoute: typeof StoreInventoryRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/earnings': {
      id: '/store/earnings'
      path: '/earnings'
      fullPath: '/store/earnings'
      preLoaderRoute: typeof StoreEarningsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/dashboard': {
      id: '/store/dashboard'
      path: '/dashboard'
      fullPath: '/store/dashboard'
      preLoaderRoute: typeof StoreDashboardRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/customers': {
      id: '/store/customers'
      path: '/customers'
      fullPath: '/store/customers'
      preLoaderRoute: typeof StoreCustomersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/analytics': {
      id: '/store/analytics'
      path: '/analytics'
      fullPath: '/store/analytics'
      preLoaderRoute: typeof StoreAnalyticsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-shopping/xml': {
      id: '/google-shopping/xml'
      path: '/google-shopping/xml'
      fullPath: '/google-shopping/xml'
      preLoaderRoute: typeof GoogleShoppingXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/3d-viewer': {
      id: '/demo/3d-viewer'
      path: '/demo/3d-viewer'
      fullPath: '/demo/3d-viewer'
      preLoaderRoute: typeof Demo3dViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studio': {
      id: '/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AdminStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storefront': {
      id: '/admin/storefront'
      path: '/storefront'
      fullPath: '/admin/storefront'
      preLoaderRoute: typeof AdminStorefrontRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image-proxy': {
      id: '/api/public/image-proxy'
      path: '/api/public/image-proxy'
      fullPath: '/api/public/image-proxy'
      preLoaderRoute: typeof ApiPublicImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/analyze-product': {
      id: '/api/ai/analyze-product'
      path: '/api/ai/analyze-product'
      fullPath: '/api/ai/analyze-product'
      preLoaderRoute: typeof ApiAiAnalyzeProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stores/$tenantId': {
      id: '/admin/stores/$tenantId'
      path: '/$tenantId'
      fullPath: '/admin/stores/$tenantId'
      preLoaderRoute: typeof AdminStoresTenantIdRouteImport
      parentRoute: typeof AdminStoresRoute
    }
    '/admin/product/$id': {
      id: '/admin/product/$id'
      path: '/product/$id'
      fullPath: '/admin/product/$id'
      preLoaderRoute: typeof AdminProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations/whatsapp': {
      id: '/admin/integrations/whatsapp'
      path: '/integrations/whatsapp'
      fullPath: '/admin/integrations/whatsapp'
      preLoaderRoute: typeof AdminIntegrationsWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminStoresRouteChildren {
  AdminStoresTenantIdRoute: typeof AdminStoresTenantIdRoute
}

const AdminStoresRouteChildren: AdminStoresRouteChildren = {
  AdminStoresTenantIdRoute: AdminStoresTenantIdRoute,
}

const AdminStoresRouteWithChildren = AdminStoresRoute._addFileChildren(
  AdminStoresRouteChildren,
)

interface AdminRouteChildren {
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlatformRoute: typeof AdminPlatformRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminStorefrontRoute: typeof AdminStorefrontRoute
  AdminStoresRoute: typeof AdminStoresRouteWithChildren
  AdminStudioRoute: typeof AdminStudioRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminIntegrationsWhatsappRoute: typeof AdminIntegrationsWhatsappRoute
  AdminProductIdRoute: typeof AdminProductIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlatformRoute: AdminPlatformRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminStorefrontRoute: AdminStorefrontRoute,
  AdminStoresRoute: AdminStoresRouteWithChildren,
  AdminStudioRoute: AdminStudioRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminIntegrationsWhatsappRoute: AdminIntegrationsWhatsappRoute,
  AdminProductIdRoute: AdminProductIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoreRouteChildren {
  StoreAnalyticsRoute: typeof StoreAnalyticsRoute
  StoreCustomersRoute: typeof StoreCustomersRoute
  StoreDashboardRoute: typeof StoreDashboardRoute
  StoreEarningsRoute: typeof StoreEarningsRoute
  StoreInventoryRoute: typeof StoreInventoryRoute
  StoreMarketingRoute: typeof StoreMarketingRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  StoreProductsRoute: typeof StoreProductsRoute
  StoreSettingsRoute: typeof StoreSettingsRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAnalyticsRoute: StoreAnalyticsRoute,
  StoreCustomersRoute: StoreCustomersRoute,
  StoreDashboardRoute: StoreDashboardRoute,
  StoreEarningsRoute: StoreEarningsRoute,
  StoreInventoryRoute: StoreInventoryRoute,
  StoreMarketingRoute: StoreMarketingRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  StoreProductsRoute: StoreProductsRoute,
  StoreSettingsRoute: StoreSettingsRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ImmersiveStoreRoute: ImmersiveStoreRoute,
  OffersRoute: OffersRoute,
  OnboardingRoute: OnboardingRoute,
  SearchRoute: SearchRoute,
  StoreRoute: StoreRouteWithChildren,
  TrackRoute: TrackRoute,
  CategoryIdRoute: CategoryIdRoute,
  Demo3dViewerRoute: Demo3dViewerRoute,
  GoogleShoppingXmlRoute: GoogleShoppingXmlRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  VendorSlugRoute: VendorSlugRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  ApiAiAnalyzeProductRoute: ApiAiAnalyzeProductRoute,
  ApiPublicImageProxyRoute: ApiPublicImageProxyRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
