create table if not exists public.whatsapp_inbox (
  id bigint generated by default as identity primary key,
  message_id text not null unique,
  chat_id text not null,
  sender_id text,
  message_type text,
  text_content text,
  media_id text,
  media_type text,
  message_timestamp bigint,
  supplier_name text,
  processing_status text not null default 'received',
  raw_metadata jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

create index if not exists whatsapp_inbox_chat_timestamp_idx
  on public.whatsapp_inbox (chat_id, message_timestamp desc);

alter table public.whatsapp_inbox enable row level security;

revoke all on table public.whatsapp_inbox from anon, authenticated;
