// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function isServerApiKey(key: string): boolean {
  if (key.startsWith("sb_secret_") && key.length > "sb_secret_".length) return true;
  const parts = key.split(".");
  if (parts.length !== 3) return false;
  try {
    // Configuration sanity check only; Supabase still verifies the signature.
    const payload = JSON.parse(Buffer.from(parts[1], "base64url").toString("utf8"));
    return payload?.role === "service_role";
  } catch {
    return false;
  }
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();

  if (!SUPABASE_URL) {
    throw new Error("SUPABASE_URL is required for server database access.");
  }
  if (!key || !isServerApiKey(key)) {
    throw new Error("SUPABASE_SERVICE_ROLE_KEY must contain a server secret or service_role key.");
  }
  return createClient<Database>(SUPABASE_URL, key, {
    global: {
      fetch: createSupabaseFetch(key),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

export type SupabaseAdminClient = ReturnType<typeof createSupabaseAdminClient>;

let _supabaseAdmin: SupabaseAdminClient | undefined;

/**
 * Return the process-local service-role client.
 *
 * The client is created lazily so Vercel/TanStack can populate server
 * environment variables before the first request. Missing credentials are a
 * configuration error and must never silently downgrade to the anon key.
 */
export function getSupabaseAdmin(): SupabaseAdminClient {
  if (!_supabaseAdmin) {
    _supabaseAdmin = createSupabaseAdminClient();
  }
  return _supabaseAdmin;
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Prefer getSupabaseAdmin() inside server handlers; the proxy remains for legacy callers.
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop) {
    if (prop === "then" || prop === "toJSON" || typeof prop === "symbol") {
      return undefined;
    }
    const client = getSupabaseAdmin();
    const value = Reflect.get(client, prop, client);

    // Preserve SupabaseClient as `this` for prototype methods such as `from`.
    return typeof value === "function" ? value.bind(client) : value;
  },
});
